spring:
  datasource:
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
        session-stat-max-count: 1000
      stat-view-servlet:
        enabled: true
        url-pattern: '/druid/*'
        login-username: admin
        login-password: admin
        reset-enable: false
      aop-patterns: com.fastree.springboot.*.service.*
    dynamic:
      primary: system
      p6spy: true
      druid:
        initial-size: 1
        min-idle: 1
        max-active: 20
        max-wait: 60000
        validation-query: 'SELECT 1'
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        async-init: true
        filters: stat,wall,slf4j
        connection-properties: config.decrypt=true;config.decrypt.key=${publickey}
        stat:
          log-slow-sql: true
          slow-sql-millis: 3000
          merge-sql: true
        wall:
          truncate-allow: false
        slf4j:
          statement-executable-sql-log-enable: true
      datasource:
        system:
          url: jdbc:mysql://localhost:3306/layui?useSSL=false&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: YVBUkpoV9jKoONqOqcBtqUTpmQy6nOiXA/G3EvVS/guy4BjYEt88gX6WHhtR/tXMntCveqxYzYPhgZfNART7zg==
          druid:
            public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMjTIf2Nm1N+Dq73AfFwyDDuQ0KhdB70dhqsXYBeyW614DSmZWuR3pB+HaIZ4bfdnfw8vRndGpSBXjRi1UczPB8CAwEAAQ==
